apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cvexporter-objects
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: cvexporter
    name: cvexporter
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: cvexporter
        deployment: cvexporter
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: cvexporter
          deployment: cvexporter
      spec:
        containers:
        - command:
          - /usr/local/bin/cvexporter
          env:
          - name: SLEEP_DURATION_SECS
            value: "300"
          - name: KUBECONFIG
            value: "/root/config"
          - name: QUAY_TOKEN
            valueFrom:
              secretKeyRef:
                key: QUAY_TOKEN
                name: cvexporter
          - name: LISTEN_PORT
            value: "8080"
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: cvexporter
          resources:
            limits:
              cpu: 100m
              memory: 600Mi
            requests:
              cpu: 10m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/config
            subPath: config
            name: cvexporter-kubeconfig
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
        volumes:
        - name: cvexporter-kubeconfig
          secret:
            defaultMode: 420
            secretName: cvexporter
            items:
            - key: KUBECONFIG
              path: config
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cvexporter
      port: metrics
    name: cvexporter-metrics
  spec:
    ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deployment: cvexporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cvexporter
      port: http
    name: cvexporter-http
  spec:
    ports:
    - name: cvexporter-http
      protocol: TCP
      port: 80
      targetPort: 8080
    selector:
      deployment: cvexporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:                                                                     
- name: IMAGE                                                                   
  value: quay.io/app-sre/cvexporter                                                 
  displayName: cvexporter image                                                     
  description: cvexporter docker image. Defaults to quay.io/app-sre/cvexporter          
- name: IMAGE_TAG                                                               
  value: "latest"                                                               
  displayName: cvexporter version                                                   
  description: cvexporter version which defaults to latest                          
