apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cvexporter-monitoring
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      prometheus: ${PROMINSTANCE}
    name: cvexporter-service-monitor
  spec:
    endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scheme: http
    namespaceSelector:
      matchNames:
      - ${TARGETNS}
    selector:
      matchLabels:
        app: cvexporter
        port: metrics
parameters:                                                                     
- name: PROMINSTANCE
  value: "app-sre"
  displayName: prometheus instance for this cluster
  description: prometheus instance for this cluster, defaults to app-sre
- name: TARGETNS
  value: "cvexporter"
  displayName: target namespace cvexporter lives in
  description: target namespace cvexporter lvies in, default "cvexporter"

