apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cvexporter
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: cvexporter
      service: cvexporter
    name: cvexporter
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: cvexporter
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: cvexporter
      spec:
        containers:
        - command:
          - /usr/local/bin/cvexporter
          env:
          - name: SLEEP_DURATION_SECS
            value: "300"
          - name: QUAY_TOKEN
            valueFrom:
              secretKeyRef:
                key: quay_token
                name: cvexporter
          image: quay.io/app-sre/cvexporter:latest
          imagePullPolicy: Always
          name: cvexporter
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 30m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      cvexporter-component: cvexporter
      service: cvexporter
    name: cvexporter
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      cvexporter-component: cvexporter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:                                                                     
- name: IMAGE                                                                   
  value: quay.io/app-sre/cvexporter                                                 
  displayName: cvexporter image                                                     
  description: cvexporter docker image. Defaults to quay.io/app-sre/cvexporter          
- name: IMAGE_TAG                                                               
  value: "latest"                                                               
  displayName: cvexporter version                                                   
  description: cvexporter version which defaults to latest                          
