apiVersion: v1
kind: Template
metadata:
  name: cvexporter
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: cvexporter
      service: cvexporter
    name: cvexporter
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: cvexporter
    template:
      metadata:
        labels:
          app: cvexporter
      spec:
        containers:
        - name: cvexporter
          image: ${IMAGE}:${IMAGE_TAG}
          command:
          - /usr/local/bin/cvexporter
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 30m
              memory: 100Mi
      app: cvexporter
parameters:
- name: IMAGE
  value: quay.io/app-sre/cvexporter
- name: IMAGE_TAG
  value: latest
- name: SLEEP_DURATION_SECS
  value: "300"
- name: POLL_INTERVAL
  value: poll_interval
